name: CI
on: push:
    branches: [ branch1 ]
  pull_request:
    branches: [ branch1 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm install
        - name: Test
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm run test:local
        - uses: actions/upload-artifact@v1
        - run: npm install
        - run: npm run build --if-present
        - run: npx wdio run ./wdio.conf.js
          if: failure()
          with:
            name: logs
            path: logs
